clone_depth: 50

configuration:
 - Debug

build:
 verbosity: minimal

image:
 - Visual Studio 2017

install:
 - pip install jinja2
 - git submodule update --init --recursive

build_script:
 - mkdir build
 - cd build
 - cmake -DNXT_USE_WERROR=1 -DNXT_ENABLE_VULKAN=1 ..
 - cmake --build .

 # TODO(cwallez@chromium.org) test on more than Debug.
 - Debug\nxt_unittests.exe
