clone_depth: 50

configuration:
 - Debug

image:
 - Visual Studio 2015

install:
 - pip install jinja2
 - git submodule update --init --recursive

build_script:
 - mkdir build
 - cd build
 - cmake ..
 - cmake --build .

 # TODO(cwallez@chromium.org) test on more than Debug.
 - src\tests\Debug\nxt_unittests.exe
