clone_depth: 50

configuration:
 - Debug

image:
 - Visual Studio 2017

install:
 - pip install jinja2
 - git submodule update --init --recursive

build_script:
 - mkdir build
 - cd build
 - cmake -DDAWN_USE_WERROR=1 -DDAWN_ENABLE_VULKAN=1 ..
 - cmake --build . -- /verbosity:minimal

 # TODO(cwallez@chromium.org) test on more than Debug.
 - Debug\dawn_unittests.exe
